package yoklamatakipsistemi;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 * @file yoklamaTakipSistemi
 * @description Bu proje, öğretmen ve öğrencilerin kayıt olup giriş yapabildiği;
 * öğretmenlerin yoklama bilgisi kaydede bildiği ve istediği öğrenciye ait
 * yoklama bilgisini görebildiği; öğrencilerin de kendilerine ait girilen
 * yoklama bilgisini gçrebildiği swing kullanılarak tasarlanmış bir yoklama sistemidir.
 * @assignment Final Proje
 * @date 14.05.2022
 * @author @beyza.yildizli@stu.fsm.edu.tr
 */

public class OgretmenFrame2 extends javax.swing.JFrame {

    Baglanti baglanti = new Baglanti();
    DefaultListModel list = new DefaultListModel();
    ArrayList seciliDersinDevamsizliklari = new ArrayList();

    //Kişisel Bilgiler:
    String tcOgrenci;
    String tcOgretmen;
    String[] ogrenciKisiselBilgileriArray = new String[4];
    String ogrenciAdi;
    int ogrenciNosu;
    int ogrenciYasi;
    String ogrenciCinsiyeti;

    public OgretmenFrame2() {
        initComponents();
    }

    public OgretmenFrame2(String tcOgretmen, String tcOgrenci, boolean koyuTema) {
        initComponents();
        liste.setModel(list);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        //Kişisel Bilgileri Tanımlama:
        this.tcOgrenci = tcOgrenci;
        this.tcOgretmen = tcOgretmen;
        ogrenciKisiselBilgileriArray = baglanti.ogrenciBilgileriArray(tcOgrenci);
        ogrenciNosu = Integer.parseInt(ogrenciKisiselBilgileriArray[1]);

        dersleriCmbyeEkle();
        genelDurumuyazdir();
        seciliDersinDevamsizliklariniYazdir();
        kisiselBilgiYazdir();

        if (koyuTema) {
            karanlikTemaYap();
            karanlikTema.setSelected(true);
            karanlikTemaPopup.setSelected(true);
            aydinlikTema.setSelected(false);
            aydinlikTemaPopup.setSelected(false);
        } else {
            aydinlikTemaYap();
            aydinlikTema.setSelected(true);
            aydinlikTemaPopup.setSelected(true);
            karanlikTema.setSelected(false);
            karanlikTemaPopup.setSelected(false);
        }
    }

    private void dersleriCmbyeEkle() {
        ArrayList derslerArrayList = new ArrayList();
        baglanti.ogrencininAldigiDersler(tcOgrenci, derslerArrayList);
        for (int i = 0; i < derslerArrayList.size(); i++) {
            dersSecCB.addItem("" + derslerArrayList.get(i));
        }
    }

    private void kisiselBilgiYazdir() {
        adSoyad.setText(ogrenciKisiselBilgileriArray[0]);
        okulNo.setText(ogrenciKisiselBilgileriArray[1]);
        tc.setText(tcOgrenci);
        yas.setText(ogrenciKisiselBilgileriArray[2]);
        cinsiyet.setText(ogrenciKisiselBilgileriArray[3]);
    }

    private void genelDurumuyazdir() {
        int girdigiDersSayisi = baglanti.girdigiDersSayisi(ogrenciNosu);
        int girmedigiDersSayisi = baglanti.girmedigiDersSayisi(ogrenciNosu);

        girdigiDerslerSayisi.setText(String.valueOf(girdigiDersSayisi));
        girmedigiDerslerSayisi.setText(String.valueOf(girmedigiDersSayisi));
        if (girdigiDersSayisi == 0 && girmedigiDersSayisi == 0) {
            devamsizlikOrani.setText("");
        } else {
            int devamsizlikYüzdesi = (100 * girmedigiDersSayisi) / (girdigiDersSayisi + girmedigiDersSayisi);
            devamsizlikOrani.setText("%" + devamsizlikYüzdesi);
        }
    }

    private void seciliDersinDevamsizliklariniYazdir() {
        list.removeAllElements();
        String ders = dersSecCB.getItemAt(dersSecCB.getSelectedIndex());
        baglanti.seciliDerseGelmedigiGünler(ogrenciNosu, ders, seciliDersinDevamsizliklari);
        if (seciliDersinDevamsizliklari.isEmpty()) {
            list.addElement("Bu derse ait devamsızlık bulunmamaktadır.");
        }
        for (int i = 0; i < seciliDersinDevamsizliklari.size(); i++) {
            list.addElement(seciliDersinDevamsizliklari.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        temaGroup = new javax.swing.ButtonGroup();
        temaPopupGroup = new javax.swing.ButtonGroup();
        popupMenu = new javax.swing.JPopupMenu();
        tema = new javax.swing.JMenu();
        aydinlikTemaPopup = new javax.swing.JRadioButtonMenuItem();
        karanlikTemaPopup = new javax.swing.JRadioButtonMenuItem();
        Hesap = new javax.swing.JMenu();
        sifreDegistirPopup = new javax.swing.JMenuItem();
        hesaptanCıkPopup = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        hesabiSilPopup = new javax.swing.JMenuItem();
        enAltPanel = new javax.swing.JPanel();
        solPanel = new javax.swing.JPanel();
        genelDurum = new javax.swing.JPanel();
        seciliPanelIsareti1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        devamsizliklar = new javax.swing.JPanel();
        seciliPanelIsareti2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kisiselBilgiler = new javax.swing.JPanel();
        seciliPanelIsareti3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sagPanel = new javax.swing.JPanel();
        genelDurumu = new javax.swing.JPanel();
        girdigiDerslerText = new javax.swing.JLabel();
        girmedigiDerslerText = new javax.swing.JLabel();
        devamsizlikOraniText = new javax.swing.JLabel();
        devamsizlikOrani = new javax.swing.JLabel();
        girmedigiDerslerSayisi = new javax.swing.JLabel();
        girdigiDerslerSayisi = new javax.swing.JLabel();
        devamsizliklari = new javax.swing.JPanel();
        gelmedigiGunlerText = new javax.swing.JLabel();
        dersSecCB = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        liste = new javax.swing.JList<>();
        kisiselBilgileri = new javax.swing.JPanel();
        kisiselBilgilerText = new javax.swing.JLabel();
        adSoyadText = new javax.swing.JLabel();
        okulNoText = new javax.swing.JLabel();
        tcText = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        adSoyad = new javax.swing.JLabel();
        okulNo = new javax.swing.JLabel();
        tc = new javax.swing.JLabel();
        yas = new javax.swing.JLabel();
        cinsiyet = new javax.swing.JLabel();
        cinsiyetText = new javax.swing.JLabel();
        yasText = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        geriMenu = new javax.swing.JMenu();
        temaMenu = new javax.swing.JMenu();
        karanlikTema = new javax.swing.JRadioButtonMenuItem();
        aydinlikTema = new javax.swing.JRadioButtonMenuItem();
        hesapMenu = new javax.swing.JMenu();
        sifreDegistir = new javax.swing.JMenuItem();
        hesaptanCıkMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        hesabiSil = new javax.swing.JMenuItem();

        tema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yoklamatakipsistemi/themes.png"))); // NOI18N
        tema.setText("TEMA");

        temaPopupGroup.add(aydinlikTemaPopup);
        aydinlikTemaPopup.setText("Aydınlık Tema");
        aydinlikTemaPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aydinlikTemaPopupActionPerformed(evt);
            }
        });
        tema.add(aydinlikTemaPopup);

        temaPopupGroup.add(karanlikTemaPopup);
        karanlikTemaPopup.setText("Karanlık Tema");
        karanlikTemaPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karanlikTemaPopupActionPerformed(evt);
            }
        });
        tema.add(karanlikTemaPopup);

        popupMenu.add(tema);

        Hesap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yoklamatakipsistemi/user menu.png"))); // NOI18N
        Hesap.setText("Hesap");

        sifreDegistirPopup.setText("Şifre Değiştir");
        sifreDegistirPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreDegistirPopupActionPerformed(evt);
            }
        });
        Hesap.add(sifreDegistirPopup);

        hesaptanCıkPopup.setText("Hesaptan Çıkış Yap");
        hesaptanCıkPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesaptanCıkPopupActionPerformed(evt);
            }
        });
        Hesap.add(hesaptanCıkPopup);
        Hesap.add(jSeparator3);

        hesabiSilPopup.setText("Hesabı Sil");
        hesabiSilPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesabiSilPopupActionPerformed(evt);
            }
        });
        Hesap.add(hesabiSilPopup);

        popupMenu.add(Hesap);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        enAltPanel.setBackground(new java.awt.Color(255, 255, 255));
        enAltPanel.setLayout(new javax.swing.BoxLayout(enAltPanel, javax.swing.BoxLayout.LINE_AXIS));

        solPanel.setBackground(new java.awt.Color(0, 102, 102));
        solPanel.setMaximumSize(new java.awt.Dimension(220, 32767));
        solPanel.setMinimumSize(new java.awt.Dimension(220, 555));
        solPanel.setPreferredSize(new java.awt.Dimension(220, 555));

        genelDurum.setBackground(new java.awt.Color(23, 131, 131));
        genelDurum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genelDurumMouseClicked(evt);
            }
        });
        genelDurum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seciliPanelIsareti1.setBackground(new java.awt.Color(0, 51, 51));
        seciliPanelIsareti1.setText(" ");
        seciliPanelIsareti1.setOpaque(true);
        genelDurum.add(seciliPanelIsareti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Genel Durum");
        genelDurum.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 120, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yoklamatakipsistemi/education.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        genelDurum.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 37, 30));

        devamsizliklar.setBackground(new java.awt.Color(0, 102, 102));
        devamsizliklar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                devamsizliklarMouseClicked(evt);
            }
        });
        devamsizliklar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seciliPanelIsareti2.setBackground(new java.awt.Color(0, 102, 102));
        seciliPanelIsareti2.setText(" ");
        seciliPanelIsareti2.setOpaque(true);
        devamsizliklar.add(seciliPanelIsareti2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yoklamatakipsistemi/task-list.png"))); // NOI18N
        devamsizliklar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, 30, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Devamsızlıkları");
        devamsizliklar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        kisiselBilgiler.setBackground(new java.awt.Color(0, 102, 102));
        kisiselBilgiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kisiselBilgilerMouseClicked(evt);
            }
        });
        kisiselBilgiler.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seciliPanelIsareti3.setBackground(new java.awt.Color(0, 102, 102));
        seciliPanelIsareti3.setText(" ");
        seciliPanelIsareti3.setOpaque(true);
        kisiselBilgiler.add(seciliPanelIsareti3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Kişisel Bilgileri");
        kisiselBilgiler.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 140, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yoklamatakipsistemi/student.png"))); // NOI18N
        kisiselBilgiler.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        javax.swing.GroupLayout solPanelLayout = new javax.swing.GroupLayout(solPanel);
        solPanel.setLayout(solPanelLayout);
        solPanelLayout.setHorizontalGroup(
            solPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(solPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genelDurum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(devamsizliklar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kisiselBilgiler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        solPanelLayout.setVerticalGroup(
            solPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(genelDurum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(devamsizliklar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(kisiselBilgiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        enAltPanel.add(solPanel);

        sagPanel.setBackground(new java.awt.Color(51, 51, 51));
        sagPanel.setLayout(new java.awt.CardLayout());

        genelDurumu.setBackground(new java.awt.Color(51, 51, 51));
        genelDurumu.setComponentPopupMenu(popupMenu);

        girdigiDerslerText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        girdigiDerslerText.setForeground(new java.awt.Color(255, 255, 255));
        girdigiDerslerText.setText("Girdiği toplam ders sayısı:");

        girmedigiDerslerText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        girmedigiDerslerText.setForeground(new java.awt.Color(255, 255, 255));
        girmedigiDerslerText.setText("Girmediği toplam ders sayısı:");

        devamsizlikOraniText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        devamsizlikOraniText.setForeground(new java.awt.Color(255, 255, 255));
        devamsizlikOraniText.setText("Devamsızlık oranı:");

        devamsizlikOrani.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        devamsizlikOrani.setForeground(new java.awt.Color(255, 255, 255));
        devamsizlikOrani.setText("5");

        girmedigiDerslerSayisi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        girmedigiDerslerSayisi.setForeground(new java.awt.Color(255, 255, 255));
        girmedigiDerslerSayisi.setText("0");

        girdigiDerslerSayisi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        girdigiDerslerSayisi.setForeground(new java.awt.Color(255, 255, 255));
        girdigiDerslerSayisi.setText("0");

        javax.swing.GroupLayout genelDurumuLayout = new javax.swing.GroupLayout(genelDurumu);
        genelDurumu.setLayout(genelDurumuLayout);
        genelDurumuLayout.setHorizontalGroup(
            genelDurumuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genelDurumuLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(genelDurumuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(girmedigiDerslerText)
                    .addComponent(girdigiDerslerText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(devamsizlikOraniText, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(genelDurumuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(genelDurumuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(girmedigiDerslerSayisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(girdigiDerslerSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(devamsizlikOrani, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        genelDurumuLayout.setVerticalGroup(
            genelDurumuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genelDurumuLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(genelDurumuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(girdigiDerslerText)
                    .addComponent(girdigiDerslerSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(genelDurumuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(girmedigiDerslerText)
                    .addComponent(girmedigiDerslerSayisi))
                .addGap(12, 12, 12)
                .addGroup(genelDurumuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(devamsizlikOraniText)
                    .addComponent(devamsizlikOrani))
                .addContainerGap(383, Short.MAX_VALUE))
        );

        sagPanel.add(genelDurumu, "card2");

        devamsizliklari.setBackground(new java.awt.Color(51, 51, 51));
        devamsizliklari.setComponentPopupMenu(popupMenu);

        gelmedigiGunlerText.setForeground(new java.awt.Color(255, 255, 255));
        gelmedigiGunlerText.setText("Seçili derste gelmediği günler:");

        dersSecCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dersSecCBİtemStateChanged(evt);
            }
        });

        jScrollPane2.setViewportView(liste);

        javax.swing.GroupLayout devamsizliklariLayout = new javax.swing.GroupLayout(devamsizliklari);
        devamsizliklari.setLayout(devamsizliklariLayout);
        devamsizliklariLayout.setHorizontalGroup(
            devamsizliklariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devamsizliklariLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(devamsizliklariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gelmedigiGunlerText, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dersSecCB, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(367, Short.MAX_VALUE))
        );
        devamsizliklariLayout.setVerticalGroup(
            devamsizliklariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devamsizliklariLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(gelmedigiGunlerText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dersSecCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        sagPanel.add(devamsizliklari, "card3");

        kisiselBilgileri.setBackground(new java.awt.Color(51, 51, 51));
        kisiselBilgileri.setComponentPopupMenu(popupMenu);

        kisiselBilgilerText.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        kisiselBilgilerText.setForeground(new java.awt.Color(255, 255, 255));
        kisiselBilgilerText.setText("KİŞİSEL BİLGİLER:");

        adSoyadText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adSoyadText.setForeground(new java.awt.Color(255, 255, 255));
        adSoyadText.setText("Ad Soyad:");

        okulNoText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        okulNoText.setForeground(new java.awt.Color(255, 255, 255));
        okulNoText.setText("Okul no:");

        tcText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tcText.setForeground(new java.awt.Color(255, 255, 255));
        tcText.setText("TC Kimlik No:");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yoklamatakipsistemi/students.png"))); // NOI18N

        adSoyad.setForeground(new java.awt.Color(255, 255, 255));
        adSoyad.setText("Ad");

        okulNo.setForeground(new java.awt.Color(255, 255, 255));
        okulNo.setText("2021111111");

        tc.setForeground(new java.awt.Color(255, 255, 255));
        tc.setText("11111111111");

        yas.setForeground(new java.awt.Color(255, 255, 255));
        yas.setText("19");

        cinsiyet.setForeground(new java.awt.Color(255, 255, 255));
        cinsiyet.setText("Kız");

        cinsiyetText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cinsiyetText.setForeground(new java.awt.Color(255, 255, 255));
        cinsiyetText.setText("Cinsiyet:");

        yasText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        yasText.setForeground(new java.awt.Color(255, 255, 255));
        yasText.setText("Yaş:");

        javax.swing.GroupLayout kisiselBilgileriLayout = new javax.swing.GroupLayout(kisiselBilgileri);
        kisiselBilgileri.setLayout(kisiselBilgileriLayout);
        kisiselBilgileriLayout.setHorizontalGroup(
            kisiselBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kisiselBilgileriLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(kisiselBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adSoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okulNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcText)
                    .addComponent(yasText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cinsiyetText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(kisiselBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cinsiyet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(okulNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adSoyad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kisiselBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kisiselBilgileriLayout.createSequentialGroup()
                        .addComponent(kisiselBilgilerText)
                        .addGap(40, 40, 40)))
                .addContainerGap())
        );
        kisiselBilgileriLayout.setVerticalGroup(
            kisiselBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kisiselBilgileriLayout.createSequentialGroup()
                .addGroup(kisiselBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kisiselBilgileriLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(kisiselBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adSoyadText)
                            .addComponent(adSoyad))
                        .addGap(12, 12, 12)
                        .addGroup(kisiselBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(okulNoText)
                            .addComponent(okulNo))
                        .addGap(12, 12, 12)
                        .addGroup(kisiselBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcText)
                            .addComponent(tc))
                        .addGap(12, 12, 12)
                        .addGroup(kisiselBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yasText)
                            .addComponent(yas))
                        .addGap(12, 12, 12)
                        .addGroup(kisiselBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cinsiyetText)
                            .addComponent(cinsiyet)))
                    .addGroup(kisiselBilgileriLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kisiselBilgilerText)))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        sagPanel.add(kisiselBilgileri, "card4");

        enAltPanel.add(sagPanel);

        getContentPane().add(enAltPanel);

        geriMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yoklamatakipsistemi/back-arrow.png"))); // NOI18N
        geriMenu.setText("Geri");
        geriMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriMenuMouseClicked(evt);
            }
        });
        menuBar.add(geriMenu);

        temaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yoklamatakipsistemi/themes.png"))); // NOI18N
        temaMenu.setText("Tema");

        temaGroup.add(karanlikTema);
        karanlikTema.setText("Karanlık Tema");
        karanlikTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karanlikTemaActionPerformed(evt);
            }
        });
        temaMenu.add(karanlikTema);

        temaGroup.add(aydinlikTema);
        aydinlikTema.setText("Aydınlık Tema");
        aydinlikTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aydinlikTemaActionPerformed(evt);
            }
        });
        temaMenu.add(aydinlikTema);

        menuBar.add(temaMenu);

        hesapMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yoklamatakipsistemi/user menu.png"))); // NOI18N
        hesapMenu.setText("Hesap");

        sifreDegistir.setText("Şifre Değiştir");
        sifreDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreDegistirActionPerformed(evt);
            }
        });
        hesapMenu.add(sifreDegistir);

        hesaptanCıkMenu.setText("Hesaptan Çıkış Yap");
        hesaptanCıkMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesaptanCıkMenuActionPerformed(evt);
            }
        });
        hesapMenu.add(hesaptanCıkMenu);
        hesapMenu.add(jSeparator2);

        hesabiSil.setText("Hesabı Sil");
        hesabiSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesabiSilActionPerformed(evt);
            }
        });
        hesapMenu.add(hesabiSil);

        menuBar.add(hesapMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genelDurumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genelDurumMouseClicked
        sagPanel.removeAll();
        sagPanel.add(genelDurumu);
        sagPanel.repaint();
        sagPanel.revalidate();

        genelDurum.setBackground(new Color(23, 131, 131));
        seciliPanelIsareti1.setBackground(new Color(0, 51, 51));

        devamsizliklar.setBackground(new Color(0, 102, 102));
        seciliPanelIsareti2.setBackground(new Color(0, 102, 102));
        kisiselBilgiler.setBackground(new Color(0, 102, 102));
        seciliPanelIsareti3.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_genelDurumMouseClicked

    private void devamsizliklarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devamsizliklarMouseClicked
        sagPanel.removeAll();
        sagPanel.add(devamsizliklari);
        sagPanel.repaint();
        sagPanel.revalidate();

        devamsizliklar.setBackground(new Color(23, 131, 131));
        seciliPanelIsareti2.setBackground(new Color(0, 51, 51));

        genelDurum.setBackground(new Color(0, 102, 102));
        seciliPanelIsareti1.setBackground(new Color(0, 102, 102));
        kisiselBilgiler.setBackground(new Color(0, 102, 102));
        seciliPanelIsareti3.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_devamsizliklarMouseClicked

    private void kisiselBilgilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kisiselBilgilerMouseClicked
        sagPanel.removeAll();
        sagPanel.add(kisiselBilgileri);
        sagPanel.repaint();
        sagPanel.revalidate();

        kisiselBilgiler.setBackground(new Color(23, 131, 131));
        seciliPanelIsareti3.setBackground(new Color(0, 51, 51));

        genelDurum.setBackground(new Color(0, 102, 102));
        seciliPanelIsareti1.setBackground(new Color(0, 102, 102));
        devamsizliklar.setBackground(new Color(0, 102, 102));
        seciliPanelIsareti2.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_kisiselBilgilerMouseClicked

    private void hesabiSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesabiSilActionPerformed
        baglanti.ogretmenSil(tcOgretmen);
        GirisYap girisYap = new GirisYap();
        girisYap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hesabiSilActionPerformed

    private void sifreDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreDegistirActionPerformed
        yeniSifreAl yeniSifreAl = new yeniSifreAl(tcOgretmen);
        yeniSifreAl.setVisible(true);
    }//GEN-LAST:event_sifreDegistirActionPerformed

    private void hesaptanCıkMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesaptanCıkMenuActionPerformed
        GirisYap girisYap = new GirisYap();
        girisYap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hesaptanCıkMenuActionPerformed

    private void geriMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriMenuMouseClicked
        OgretmenIlkFrame ogretmenIlkFrame = new OgretmenIlkFrame(tcOgretmen);
        ogretmenIlkFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_geriMenuMouseClicked

    private void aydinlikTemaPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aydinlikTemaPopupActionPerformed
        aydinlikTemaYap();
        aydinlikTema.setSelected(true);
        karanlikTema.setSelected(false);
    }//GEN-LAST:event_aydinlikTemaPopupActionPerformed

    private void karanlikTemaPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karanlikTemaPopupActionPerformed
        karanlikTemaYap();
        karanlikTema.setSelected(true);
        aydinlikTema.setSelected(false);
    }//GEN-LAST:event_karanlikTemaPopupActionPerformed

    private void aydinlikTemaYap() {
        Color panelRengi = new Color(204, 204, 204);
        Color yaziRengi = Color.BLACK;
        renkDegis(panelRengi, yaziRengi);
    }

    private void karanlikTemaYap() {
        Color panelRengi = new Color(51, 51, 51);
        Color yaziRengi = Color.WHITE;
        renkDegis(panelRengi, yaziRengi);
    }

    private void renkDegis(Color panelRengi, Color yaziRengi) {
        genelDurumu.setBackground(panelRengi);
        devamsizliklari.setBackground(panelRengi);
        kisiselBilgileri.setBackground(panelRengi);
        gelmedigiGunlerText.setForeground(yaziRengi);
        girdigiDerslerText.setForeground(yaziRengi);
        girmedigiDerslerText.setForeground(yaziRengi);
        devamsizlikOraniText.setForeground(yaziRengi);
        girdigiDerslerSayisi.setForeground(yaziRengi);
        girmedigiDerslerSayisi.setForeground(yaziRengi);
        devamsizlikOrani.setForeground(yaziRengi);
        adSoyadText.setForeground(yaziRengi);
        okulNoText.setForeground(yaziRengi);
        tcText.setForeground(yaziRengi);
        yasText.setForeground(yaziRengi);
        cinsiyetText.setForeground(yaziRengi);
        adSoyad.setForeground(yaziRengi);
        okulNo.setForeground(yaziRengi);
        tc.setForeground(yaziRengi);
        yas.setForeground(yaziRengi);
        cinsiyet.setForeground(yaziRengi);
        kisiselBilgilerText.setForeground(yaziRengi);
    }

    private void sifreDegistirPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreDegistirPopupActionPerformed
        yeniSifreAl yeniSifreAl = new yeniSifreAl(tcOgretmen);
        yeniSifreAl.setVisible(true);
    }//GEN-LAST:event_sifreDegistirPopupActionPerformed

    private void hesaptanCıkPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesaptanCıkPopupActionPerformed
        GirisYap girisYap = new GirisYap();
        girisYap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hesaptanCıkPopupActionPerformed

    private void hesabiSilPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesabiSilPopupActionPerformed
        baglanti.ogretmenSil(tcOgretmen);
        GirisYap girisYap = new GirisYap();
        girisYap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hesabiSilPopupActionPerformed

    private void aydinlikTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aydinlikTemaActionPerformed
       aydinlikTemaYap();
       aydinlikTemaPopup.setSelected(true);
        karanlikTemaPopup.setSelected(false);
    }//GEN-LAST:event_aydinlikTemaActionPerformed

    private void karanlikTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karanlikTemaActionPerformed
       karanlikTemaYap();
       karanlikTemaPopup.setSelected(true);
       aydinlikTemaPopup.setSelected(false);
    }//GEN-LAST:event_karanlikTemaActionPerformed

    private void dersSecCBİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dersSecCBİtemStateChanged
        seciliDersinDevamsizliklariniYazdir();
    }//GEN-LAST:event_dersSecCBİtemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Hesap;
    private javax.swing.JLabel adSoyad;
    private javax.swing.JLabel adSoyadText;
    private javax.swing.JRadioButtonMenuItem aydinlikTema;
    private javax.swing.JRadioButtonMenuItem aydinlikTemaPopup;
    private javax.swing.JLabel cinsiyet;
    private javax.swing.JLabel cinsiyetText;
    private javax.swing.JComboBox<String> dersSecCB;
    private javax.swing.JLabel devamsizlikOrani;
    private javax.swing.JLabel devamsizlikOraniText;
    private javax.swing.JPanel devamsizliklar;
    private javax.swing.JPanel devamsizliklari;
    private javax.swing.JPanel enAltPanel;
    private javax.swing.JLabel gelmedigiGunlerText;
    private javax.swing.JPanel genelDurum;
    private javax.swing.JPanel genelDurumu;
    private javax.swing.JMenu geriMenu;
    private javax.swing.JLabel girdigiDerslerSayisi;
    private javax.swing.JLabel girdigiDerslerText;
    private javax.swing.JLabel girmedigiDerslerSayisi;
    private javax.swing.JLabel girmedigiDerslerText;
    private javax.swing.JMenuItem hesabiSil;
    private javax.swing.JMenuItem hesabiSilPopup;
    private javax.swing.JMenu hesapMenu;
    private javax.swing.JMenuItem hesaptanCıkMenu;
    private javax.swing.JMenuItem hesaptanCıkPopup;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JRadioButtonMenuItem karanlikTema;
    private javax.swing.JRadioButtonMenuItem karanlikTemaPopup;
    private javax.swing.JPanel kisiselBilgiler;
    private javax.swing.JLabel kisiselBilgilerText;
    private javax.swing.JPanel kisiselBilgileri;
    private javax.swing.JList<String> liste;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel okulNo;
    private javax.swing.JLabel okulNoText;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JPanel sagPanel;
    private javax.swing.JLabel seciliPanelIsareti1;
    private javax.swing.JLabel seciliPanelIsareti2;
    private javax.swing.JLabel seciliPanelIsareti3;
    private javax.swing.JMenuItem sifreDegistir;
    private javax.swing.JMenuItem sifreDegistirPopup;
    private javax.swing.JPanel solPanel;
    private javax.swing.JLabel tc;
    private javax.swing.JLabel tcText;
    private javax.swing.JMenu tema;
    private javax.swing.ButtonGroup temaGroup;
    private javax.swing.JMenu temaMenu;
    private javax.swing.ButtonGroup temaPopupGroup;
    private javax.swing.JLabel yas;
    private javax.swing.JLabel yasText;
    // End of variables declaration//GEN-END:variables
}
