package yoklamatakipsistemi;

import javax.swing.JFrame;

/**
 * @file yoklamaTakipSistemi
 * @description Bu proje, öğretmen ve öğrencilerin kayıt olup giriş yapabildiği;
 * öğretmenlerin yoklama bilgisi kaydede bildiği ve istediği öğrenciye ait
 * yoklama bilgisini görebildiği; öğrencilerin de kendilerine ait girilen
 * yoklama bilgisini görebildiği swing kullanılarak tasarlanmış bir yoklama sistemidir.
 * @assignment Final Proje
 * @date 14.05.2022
 * @author @beyza.yildizli@stu.fsm.edu.tr
 */

public class yeniSifreAl extends javax.swing.JFrame {

    Baglanti baglanti = new Baglanti();
    String tcNo;

    /**
     * Creates new form yeniSifreAl
     */
    public yeniSifreAl() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public yeniSifreAl(String tc) {
        initComponents();
        uyari1.setText(" ");
        uyari2.setText(" ");
        uyari3.setText(" ");
        tcNo = tc;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uyari3 = new javax.swing.JLabel();
        uyari1 = new javax.swing.JLabel();
        uyari2 = new javax.swing.JLabel();
        myButton1 = new yoklamatakipsistemi.MyButton();
        oncekiSifre = new javax.swing.JPasswordField();
        yeniSifre = new javax.swing.JPasswordField();
        yeniSifreTekrar = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(245, 400));
        setMinimumSize(new java.awt.Dimension(245, 400));
        setPreferredSize(new java.awt.Dimension(245, 400));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(245, 362));
        jPanel1.setMinimumSize(new java.awt.Dimension(245, 362));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Önceki şifreniz:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Yeni şifreniz:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Yeni şifreniz (tekrar):");

        uyari3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        uyari3.setForeground(new java.awt.Color(255, 51, 51));
        uyari3.setText("Önceki şifre hatalı!");

        uyari1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        uyari1.setForeground(new java.awt.Color(255, 51, 51));
        uyari1.setText("Önceki şifre hatalı!");

        uyari2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        uyari2.setForeground(new java.awt.Color(255, 51, 51));
        uyari2.setText("Önceki şifre hatalı!");

        myButton1.setBackground(new java.awt.Color(204, 204, 204));
        myButton1.setText("ONAYLA");
        myButton1.setBorderColor(new java.awt.Color(0, 0, 0));
        myButton1.setColor(new java.awt.Color(204, 204, 204));
        myButton1.setColorClick(new java.awt.Color(218, 218, 218));
        myButton1.setColorOver(new java.awt.Color(204, 204, 204));
        myButton1.setRadius(30);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(yeniSifreTekrar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uyari2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(uyari1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uyari3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oncekiSifre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yeniSifre, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 62, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oncekiSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uyari1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(uyari2)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yeniSifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(uyari3)
                .addGap(18, 18, 18)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        Generics<String> g = new Generics<>(oncekiSifre.getText());
        String oncekiSifresi =  g.getSifre();
        String yeniSifresi = yeniSifre.getText();
        String tekrarYeniSifresi = yeniSifreTekrar.getText();
        uyari1.setText(" ");
        uyari2.setText(" ");
        uyari3.setText(" ");
        if (oncekiSifresi.isEmpty()) {
            uyari1.setText("Burası boş bırakılamaz!");
        }
        if (yeniSifresi.isEmpty()) {
            uyari2.setText("Burası boş bırakılamaz!");
        }
        if (tekrarYeniSifresi.isEmpty()) {
            uyari3.setText("Burası boş bırakılamaz!");
        }
        if (oncekiSifresi.isEmpty() == false && yeniSifresi.isEmpty() == false && tekrarYeniSifresi.isEmpty() == false) {
            if (baglanti.sifreDogruMu(tcNo, oncekiSifresi)) {
                if (yeniSifresi.compareTo(tekrarYeniSifresi) == 0) {
                    baglanti.sifreDegis(tcNo, yeniSifresi);
                    this.dispose();
                } else {
                    uyari3.setText("Şifreler eşleşmiyor!");
                }
            } else {
                uyari1.setText("Önceki şifreniz yanlış!");
            }
        }
    }//GEN-LAST:event_myButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private yoklamatakipsistemi.MyButton myButton1;
    private javax.swing.JPasswordField oncekiSifre;
    private javax.swing.JLabel uyari1;
    private javax.swing.JLabel uyari2;
    private javax.swing.JLabel uyari3;
    private javax.swing.JPasswordField yeniSifre;
    private javax.swing.JPasswordField yeniSifreTekrar;
    // End of variables declaration//GEN-END:variables
}
